#!/bin/env bash
# My rofi config menu to quickly edit some config files

# What's Shown To The User
chosen=$(printf "# Cli/TUI Configs\nKitty Config\nBash Confign\nZsh Config\nEnv Config\nAlias Config\nFunctions Config\nProfile Config\nStarship Config\nNeovim Config\nNeofetch Config\nLf Config\n \n# GUI Configs\nXsession Config\nXresources Config\nHyprland Config\nWaybar Config\nWaybar Style\nRofi Config\nMimeapps List Config" | rofi -dmenu -i -theme "nord" -theme-str "window {width: 14em;} listview {lines: 21;}")

# Open What Is Chosen
case "$chosen" in

# Cli Or Tui Configs
  "Kitty Config") kitty -e nvim $XDG_CONFIG_HOME/kitty/kitty.conf ;;
	"Bash Config") kitty -e nvim $HOME/.bashrc ;;
	"Zsh Config") kitty -e nvim $HOME/.zshrc ;;
	"Env Config") kitty -e nvim $HOME/.zshenv ;;
	"Alias Config") kitty -e nvim $HOME/.aliasrc ;;
	"Functions Config") kitty -e nvim $HOME/.functionrc ;;
	"Profile Config") kitty -e nvim $HOME/.profile ;;
	"Starship Config") kitty -e nvim $XDG_CONFIG_HOME/starship.toml ;;
	"Neovim Config") kitty -e nvim $XDG_CONFIG_HOME/nvim/init.lua ;;
	"Neofetch Config") kitty -e nvim $XDG_CONFIG_HOME/neofetch/config.conf ;;
	"Lf Config") kitty -e nvim $XDG_CONFIG_HOME/lf/lfrc ;;

# GUI Configs
	"Hyprland Config") kitty -e nvim $XDG_CONFIG_HOME/hypr/hyprland.conf ;;
	"Waybar Config") kitty -e nvim $XDG_CONFIG_HOME/waybar/config ;;
	"Waybar Style") kitty -e nvim $XDG_CONFIG_HOME/waybar/style.css ;;
	"Rofi Config") kitty -e nvim $XDG_CONFIG_HOME/rofi/config.rasi ;;
  "Mimeapps List Config") kitty -e nvim $XDG_CONFIG_HOME/mimeapps.list ;;

# If Non Chosen Exit
	*) exit 1 ;;
esac
